### ISSUE TITLE
Implementing Error

### ISSUE THREAD

**Issue by qmin2** [voidism/DiffCSE#10]
I've been trying to run your codes, but for some reason, it seems like it doesn't work on my settings.

I ran into this error mentioned below. 

Is there any solution?

```
warnings.warn('Was asked to gather along dimension 0, but all '
Traceback (most recent call last):
  File "train.py", line 600, in <module>
    main()
  File "train.py", line 564, in main
    train_result = trainer.train(model_path=model_path)
  File "/home/qmin/DiffCSE/diffcse/trainers.py", line 514, in train
    tr_pos_sim += model.sim.pos_avg
  File "/home/qmin/anaconda3/envs/diffcse/lib/python3.7/site-packages/torch/nn/modules/module.py", line 779, in __getattr__
    type(self).__name__, name))
torch.nn.modules.module.ModuleAttributeError: 'DataParallel' object has no attribute 'sim'
```

**Comment by qmin2** [comment]
changing model.sim.pos_avg to model.module.sim.pos_avg in trainers.py line 514~519 makes code work

```
tr_pos_sim += model.module.sim.pos_avg
tr_neg_sim += model.module.sim.neg_avg
tr_others["electra_acc"] += model.module.electra_acc
tr_others["electra_rep_acc"] += model.module.electra_rep_acc
tr_others["electra_fix_acc"] += model.module.electra_fix_acc
```

**Comment by qmin2** [comment]
changing model.sim.pos_avg to model.module.sim.pos_avg in trainers.py line 514~519 makes code work
```
tr_pos_sim += model.module.sim.pos_avg
tr_neg_sim += model.module.sim.neg_avg
tr_others["electra_acc"] += model.module.electra_acc
tr_others["electra_rep_acc"] += model.module.electra_rep_acc
tr_others["electra_fix_acc"] += model.module.electra_fix_acc
```
