### ISSUE TITLE
torch.nn.modules.module.ModuleAttributeError: 'DataParallel' object has no attribute 'sim'

### ISSUE THREAD

**Issue by lizhaohuigit1** [voidism/DiffCSE#5]
Traceback (most recent call last):
  File "/home/lizhaohui/DiffCSE/train.py", line 600, in <module>
    main()
  File "/home/lizhaohui/DiffCSE/train.py", line 564, in main
    train_result = trainer.train(model_path=model_path)
  File "/home/lizhaohui/DiffCSE/diffcse/trainers.py", line 514, in train
    tr_pos_sim += model.sim.pos_avg
  File "/home/lizhaohui/miniconda3/envs/py395/lib/python3.9/site-packages/torch/nn/modules/module.py", line 778, in __getattr__
    raise ModuleAttributeError("'{}' object has no attribute '{}'".format(
torch.nn.modules.module.ModuleAttributeError: 'DataParallel' object has no attribute 'sim'
  0%|                                                                                          | 0/7814 [00:11<?, ?it/s]

**Comment by gunny97** [comment]
How did you solve out the problem?

**Comment by yiren-jian** [comment]
> 

CUDA_VISIBLE_DEVICES=0

**Comment by gunny97** [comment]
Thank you :D
